# Generated by Django 3.2 on 2023-02-16 23:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('12.00')), django.core.validators.MaxValueValidator(Decimal('250.00'))]),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('GEL', 'Gel'), ('SHELLAC', 'Shellac'), ('BROWS', 'Brows'), ('HENNA', 'Henna')], max_length=20),
        ),
    ]
