# Generated by Django 3.2 on 2023-03-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230216_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('GEL', 'Gel'), ('SHELLAC', 'Shellac'), ('MANICURE', 'Manicure'), ('BROWS', 'Brows'), ('HENNA', 'Henna'), ('SHAPE_TINT', 'Shape_tint')], max_length=20),
        ),
    ]
