# Generated by Django 3.2 on 2023-02-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created',
        ),
    ]
